replicaCount: 2

image:
  repository: kuberouteops/catalog
  tag: "0.3.0"

database:
  url: jdbc:mysql://catalog-mysql:3306/catalog
  existingSecret: catalog-mysql-secret

ingress:
  className: nginx
  host: kuberouteops.test